GMAIL_USERNAME: 'abc1zbq'
GMAIL_PASSWORD: 'nguyenbach'
GG_DRVIER_CLIENT_ID: '782071649992-7uhe1uifqf6rvrp9veqaqf2o545tcmkl.apps.googleusercontent.com'
GG_DRVIER_CLIENT_SECRET: 'PHtDN-lquWfrsPr7yXsD060p'
GG_DRVIER_ACCESS_TOKEN: 'ya29.PwLqLpDs8kKZBoYjSAxO96zo9PIKcZrgSDIMA4WepZqvUWmj2s69QeIdCxdxNwjRC_Wc'
GG_DRVIER_REFRESH_TOKEN: '/KJjTIHGy9KS_Y38v4vXf1r9HDE6MUqJKusYlk7bnG0VIgOrJDtdun6zK6XiATCKT'
